# Generated by Django 4.2.11 on 2024-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
                ('bookname', models.CharField(max_length=20, verbose_name='Bname')),
                ('bookgenere', models.CharField(max_length=20, verbose_name='Bgenere')),
                ('bcost', models.FloatField()),
            ],
        ),
    ]
