# Generated by Django 5.0.3 on 2024-04-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectid', models.IntegerField()),
                ('subjectname', models.CharField(max_length=20)),
                ('subjectmark', models.CharField(max_length=20)),
                ('subjectmedium', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
